title: Code review with spiros
email: spirosmag@ieee.org | Spiros.Maggioros@pennmedicine.upenn.edu
description: Weekly tech news and code reviews(bashing)
baseurl: ""
url: "github.com/spirosmaggioros"
github_username: spirosmaggioros

permalink: /:slug.html

favicon: "pixelated.png"

# Build settings
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
