title: Spiros Maggioros
email: spirosmag@ieee.org | Spiros.Maggioros@pennmedicine.upenn.edu
description:
  I am Spiros Maggioros, a Research Software Engineer at Penn Medicine - University of Pennsylvania, currently working
  on the NiChart Project(neuroimagingchart.com). I also study Electrical and Computer Engineering at National Technical
  University of Athens, currently on my 4th year. My work focuses on Algorithms and Optimization, Machine Learning,
  Software Engineering and Programming Languages. My biggest project to date is AlgoPlus, a C++17 library for complex
  data structures and algorithms with 180+ stars on GitHub. My latest publication is "Wildfire danger prediction optimization
  with transfer learning" that helps with wildfire danger prediction and very soon the NiChart insights paper will come out
  at AAAI 2025 conference.
baseurl: ""
url: "github.com/spirosmaggioros"
github_username: spirosmaggioros

permalink: /:slug.html

favicon: "pixelated.png"

# Build settings
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
